# Generated by Django 4.1.7 on 2023-07-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_geolocation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='geolocation',
            managers=[
            ],
        ),
    ]
