# Generated by Django 4.1.7 on 2023-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_geolocation_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
