# Generated by Django 4.1.7 on 2023-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hashtag', models.CharField(max_length=100)),
                ('cover', models.ImageField(default='no image', upload_to='')),
                ('likes', models.IntegerField()),
                ('comments_counter', models.IntegerField()),
                ('save_counter', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
