# Generated by Django 4.1.7 on 2023-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='save_counter',
            field=models.IntegerField(null=True),
        ),
    ]
