# Generated by Django 4.1.7 on 2023-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_comments_counter_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='save_counter',
            field=models.IntegerField(default=0),
        ),
    ]
