# Generated by Django 4.1.7 on 2023-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_comments_counter_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='no image', upload_to=''),
        ),
    ]
