# Generated by Django 4.1.7 on 2023-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='save_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
