# Generated by Django 4.1.7 on 2023-06-18 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_comment_related_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('image', models.ImageField(default='no_image', upload_to='')),
                ('likes_counter', models.IntegerField(default=0)),
                ('replies_counter', models.IntegerField(default=0)),
                ('related_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reply')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
