# Generated by Django 4.1.7 on 2023-06-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment_replies_counter_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='related_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
    ]
